### ISSUE TITLE
Wrong time - End of Daylight saving time

### ISSUE THREAD

**Issue by Proulxs** [SpegalDev/Wilderness#1]
Hi from Canada,

Daylight saving time ended this night and now the Wilderness Flash Events Notifier is 1h off on the timing. I checked for UK daylight saving end thinking it would fix itself once UK also change back but apparently they already did so not sure if I am supposed to do something to fix it on my end?

Thanks, ProulxS

**Comment by SpegalDev** [comment]
I have updated the times, thank you for the report!
